### PR TITLE
Hardcoded dcs

### PR DESCRIPTION
**Pull request by goodmind**
@leonerd can you test this?

### CODE REVIEW

**Comment by leonerd** [comment]
Uhhm.. maybe? How might I go about installing it to try it?

**Comment by goodmind** [comment]
From git branch?

```
npm install goodmind/telegram.link#hardcoded-dcs
```

**Comment by goodmind** [comment]
@leonerd is this works?

**Comment by leonerd** [comment]
@goodmind - I believe so. A little hard to tell because I still keep getting a few of those HTML-level 404 error message bodies, but I have managed to call `auth.sendCode()` successfully, resulting in another code being sent to my device.

One thing I'd suggest though is that the API shape here seems a bit wrong. The `callback` argument really should be the last in the list. You might have to do something fun with inspecting types to see what was where.

**Comment by goodmind** [comment]
@leonerd this is for backwards compatibility

**Comment by leonerd** [comment]
Yes, you can keep it backwards compatible:

    function getDataCenters() {
      var hardcode; var callback;
      if (typeof arguments[0] === "boolean") {
        hardcode = arguments[0];
        callback = arguments[1];
      }
      else {
        hardcode = false;
        callback = arguments[0];
      }
    }

Thus ensuring any of

    getDataCenters()
    getDataCenters(true)
    getDataCenters(function () { ... })
    getDataCenters(true, function () { ... })

do the right thing

**Comment by arcanjoqt** [comment]
All of those 404 that I was receiving at the time were caused by this [GET](https://github.com/goodmind/telegram-mt-node/blob/master/lib/net/http-connection.js#L72) 
because I was sending nothing to Telegram. Some other call was deleting all the the contents to be sent, so I tested changing [this line](https://github.com/goodmind/telegram-mt-node/blob/master/lib/net/rpc-channel.js#L69) to get a new connection every time end those 404 errors seems to be gone.

**Pull request closed without merging**
